version: "3.0"
services:
  redis:
    image: redis
  db:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5431:5432"

  web:
    environment:
      - NODE_ENV= development
      - DB_HOST=${DB_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - BASE_URL=${BASE_URL}
    build:
      context: .
      args:
        - PORT:${PORT}
    volumes:
      - ./:/usr/app
    container_name: irembo
    working_dir: /usr/app
    depends_on:
      - db
      - redis
    ports: 
      - "5000:4000"
    restart: always
